package com.example.simplenofap.localization

import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.unit.LayoutDirection
import com.example.simplenofap.settings.LanguagePreference
import com.example.simplenofap.counter.CounterUnitLabels
import com.example.simplenofap.counter.EnglishCounterUnitLabels
import java.time.LocalDate
import java.time.format.DateTimeFormatter
import java.util.Locale

enum class ResolvedLanguage(
    val layoutDirection: LayoutDirection
) {
    English(LayoutDirection.Ltr),
    Hebrew(LayoutDirection.Rtl)
}

data class AppStrings(
    val appName: String,
    val main: String,
    val notifications: String,
    val settings: String,
    val counter: String,
    val dayStreaks: String,
    val language: String,
    val languageEnglish: String,
    val languageHebrew: String,
    val languageSystem: String,
    val theme: String,
    val themeLight: String,
    val themeDark: String,
    val themeSystem: String,
    val profile: String,
    val name: String,
    val namePlaceholder: String,
    val nameSupportingText: String,
    val nameRequired: String,
    val nameSaved: String,
    val save: String,
    val appearance: String,
    val appearanceDescription: String,
    val languageDescription: String,
    val about: String,
    val version: String,
    val versionUnavailable: String,
    val aboutPurpose: String,
    val unitedStatesFlag: String,
    val israelFlag: String,
    val mainPlaceholder: String,
    val counterPlaceholder: String,
    val dayStreaksPlaceholder: String,
    val dayStreakThreeDaysName: String,
    val dayStreakOneWeekName: String,
    val dayStreakThreeWeeksName: String,
    val dayStreakOneMonthName: String,
    val dayStreakTwoMonthsName: String,
    val dayStreakThresholdDays: (Int) -> String,
    val dayStreakOverview: String,
    val dayStreakNextAchievement: String,
    val dayStreakAllAchievementsEarned: String,
    val dayStreakRemainingTime: (Long, Long, Long) -> String,
    val dayStreakAvailableRewards: String,
    val dayStreakCurrentAttempt: String,
    val dayStreakEarned: String,
    val dayStreakLocked: String,
    val dayStreakAvailableCount: (Int) -> String,
    val dayStreakHistory: String,
    val dayStreakNoHistory: String,
    val dayStreakEarnedAt: (String) -> String,
    val dayStreakUsedAt: (String) -> String,
    val dayStreakCooldownReady: String,
    val dayStreakCooldownWaiting: (String) -> String,
    val dayStreakCelebrationTitle: String,
    val dayStreakCelebrationBody: (String) -> String,
    val dismiss: String,
    val relapseTitle: String,
    val relapseUseRewardBody: String,
    val relapseNoRewardBody: String,
    val relapseCooldownBody: (String) -> String,
    val resetAnyway: String,
    val useReward: String,
    val rewardUseFailed: String,
    val dayStreakThreeDaysNotificationTitle: String,
    val dayStreakThreeDaysNotificationBody: String,
    val dayStreakOneWeekNotificationTitle: String,
    val dayStreakOneWeekNotificationBody: String,
    val dayStreakThreeWeeksNotificationTitle: String,
    val dayStreakThreeWeeksNotificationBody: String,
    val dayStreakOneMonthNotificationTitle: String,
    val dayStreakOneMonthNotificationBody: String,
    val dayStreakTwoMonthsNotificationTitle: String,
    val dayStreakTwoMonthsNotificationBody: String,
    val notificationsPlaceholder: String,
    val settingsPlaceholder: String,
    val openMenu: String,
    val addNotification: String,
    val noNotifications: String,
    val noNotificationsBody: String,
    val editNotification: String,
    val newNotification: String,
    val cancel: String,
    val delete: String,
    val deleteNotificationTitle: String,
    val deleteNotificationBody: String,
    val discardChangesTitle: String,
    val discardChangesBody: String,
    val discard: String,
    val keepEditing: String,
    val message: String,
    val messageOptional: String,
    val sound: String,
    val defaultSound: String,
    val silent: String,
    val chooseSound: String,
    val weekdaysRequired: String,
    val notificationPermissionWarning: String,
    val grantPermission: String,
    val exactAlarmWarning: String,
    val allowExactAlarms: String,
    val notificationBehavior: String,
    val notificationBehaviorDescription: String,
    val normalReminderNotifications: String,
    val fullScreenReminderAlerts: String,
    val fullScreenPermissionUnavailableWarning: String,
    val openAndroidSettings: String,
    val fullScreenAlertDismiss: String,
    val fullScreenAlertOpenApp: String,
    val notificationError: String,
    val notificationDefaultBody: String,
    val myStreak: String,
    val changeStartTime: String,
    val resetToNow: String,
    val resetCounterTitle: String,
    val resetCounterBody: String,
    val confirmReset: String,
    val counterStartedAt: String,
    val counterAccessibility: (Long, Long, Long, Long) -> String,
    val startTimeFutureError: String,
    val datePickerTitle: String,
    val datePickerHeadline: (LocalDate) -> String,
    val counterUnitLabels: CounterUnitLabels,
    val weekdayInitials: List<String>,
    val weekdayNames: List<String>
)

val LocalAppStrings = staticCompositionLocalOf { EnglishStrings }

fun resolveLanguagePreference(languagePreference: LanguagePreference): ResolvedLanguage {
    return when (languagePreference) {
        LanguagePreference.English -> ResolvedLanguage.English
        LanguagePreference.Hebrew -> ResolvedLanguage.Hebrew
        LanguagePreference.System -> {
            if (Locale.getDefault().language.equals("he", ignoreCase = true)) {
                ResolvedLanguage.Hebrew
            } else {
                ResolvedLanguage.English
            }
        }
    }
}

fun stringsFor(language: ResolvedLanguage): AppStrings {
    return when (language) {
        ResolvedLanguage.English -> EnglishStrings
        ResolvedLanguage.Hebrew -> HebrewStrings
    }
}

private val EnglishDatePickerHeadlineFormatter = DateTimeFormatter.ofPattern("MMM d, yyyy", Locale.ENGLISH)
private val HebrewDatePickerHeadlineFormatter = DateTimeFormatter.ofPattern("d בMMMM yyyy", Locale.forLanguageTag("he"))

private val EnglishStrings = AppStrings(
    appName = "SimpleNoFap",
    main = "Main",
    notifications = "Notification Manager",
    settings = "Settings",
    counter = "Counter",
    dayStreaks = "Day-Streaks",
    language = "Language",
    languageEnglish = "English",
    languageHebrew = "Hebrew",
    languageSystem = "System",
    theme = "Theme",
    themeLight = "Light",
    themeDark = "Dark",
    themeSystem = "System",
    profile = "Profile",
    name = "Name",
    namePlaceholder = "How should we call you?",
    nameSupportingText = "Used to make encouragement feel personal.",
    nameRequired = "Name is required.",
    nameSaved = "Name saved.",
    save = "Save",
    appearance = "Appearance",
    appearanceDescription = "Choose how SimpleNoFap looks on this device.",
    languageDescription = "Choose the language and reading direction.",
    about = "About",
    version = "Version",
    versionUnavailable = "Unavailable",
    aboutPurpose = "A simple, private companion for staying focused on your streak.",
    unitedStatesFlag = "United States flag",
    israelFlag = "Israel flag",
    mainPlaceholder = "Main screen placeholder",
    counterPlaceholder = "The streak counter will live here.",
    dayStreaksPlaceholder = "Recent and available Day-Streak badges will live here.",
    dayStreakThreeDaysName = "Three days",
    dayStreakOneWeekName = "One week",
    dayStreakThreeWeeksName = "Three weeks",
    dayStreakOneMonthName = "One month",
    dayStreakTwoMonthsName = "Two months",
    dayStreakThresholdDays = { days -> "$days days" },
    dayStreakOverview = "Achievements",
    dayStreakNextAchievement = "Next achievement",
    dayStreakAllAchievementsEarned = "All achievements earned for this attempt",
    dayStreakRemainingTime = { days, hours, minutes -> "${days}d ${hours}h ${minutes}m remaining" },
    dayStreakAvailableRewards = "Available rewards",
    dayStreakCurrentAttempt = "Current attempt",
    dayStreakEarned = "Earned",
    dayStreakLocked = "Locked",
    dayStreakAvailableCount = { count -> "$count available" },
    dayStreakHistory = "Recent history",
    dayStreakNoHistory = "No Day-Streak rewards yet.",
    dayStreakEarnedAt = { value -> "Earned $value" },
    dayStreakUsedAt = { value -> "Used $value" },
    dayStreakCooldownReady = "Reward save is ready.",
    dayStreakCooldownWaiting = { value -> "Reward save cooldown: $value remaining" },
    dayStreakCelebrationTitle = "Day-Streak unlocked",
    dayStreakCelebrationBody = { name -> "$name reward added to your saves." },
    dismiss = "Dismiss",
    relapseTitle = "Relapse support",
    relapseUseRewardBody = "Use one available Day-Streak reward to save your current counter.",
    relapseNoRewardBody = "No Day-Streak reward is available yet. You can reset the counter and begin a new attempt.",
    relapseCooldownBody = { value -> "A reward was used recently. You can save again in $value, or reset now." },
    resetAnyway = "Reset anyway",
    useReward = "Use reward",
    rewardUseFailed = "That reward could not be used. Please try again.",
    dayStreakThreeDaysNotificationTitle = "Three days strong!",
    dayStreakThreeDaysNotificationBody = "You made it through the first three days. Keep building your momentum is real.",
    dayStreakOneWeekNotificationTitle = "One full week!",
    dayStreakOneWeekNotificationBody = "Seven days of persistence. You proved to yourself that you have the strength to continue.",
    dayStreakThreeWeeksNotificationTitle = "Three weeks strong!",
    dayStreakThreeWeeksNotificationBody = "Twenty-one days of choosing yourself. Your commitment is becoming a habit.",
    dayStreakOneMonthNotificationTitle = "One full month!",
    dayStreakOneMonthNotificationBody = "Thirty days of commitment. This is a major achievement protect what you have built.",
    dayStreakTwoMonthsNotificationTitle = "Two powerful months!",
    dayStreakTwoMonthsNotificationBody = "Sixty days of persistence. You have come far, and the strength to continue is yours.",
    notificationsPlaceholder = "Scheduled notification management will live here.",
    settingsPlaceholder = "App preferences for the skeleton.",
    openMenu = "Open menu",
    addNotification = "Add notification",
    noNotifications = "No reminders yet",
    noNotificationsBody = "Add a weekly reminder to keep your streak in focus.",
    editNotification = "Edit reminder",
    newNotification = "New reminder",
    cancel = "Cancel",
    delete = "Delete",
    deleteNotificationTitle = "Delete this reminder?",
    deleteNotificationBody = "This reminder and its scheduled alarm will be removed.",
    discardChangesTitle = "Discard changes?",
    discardChangesBody = "Your unsaved changes will be lost.",
    discard = "Discard",
    keepEditing = "Keep editing",
    message = "Message",
    messageOptional = "Optional encouragement",
    sound = "Sound",
    defaultSound = "System default",
    silent = "Silent",
    chooseSound = "Choose sound",
    weekdaysRequired = "Choose at least one day.",
    notificationPermissionWarning = "Notifications are blocked. Active reminders are saved but cannot be delivered.",
    grantPermission = "Allow notifications",
    exactAlarmWarning = "Exact alarm access is off. Reminders may arrive a little late.",
    allowExactAlarms = "Alarms & reminders",
    notificationBehavior = "Notification behavior",
    notificationBehaviorDescription = "Choose how scheduled reminders appear.",
    normalReminderNotifications = "Normal notifications",
    fullScreenReminderAlerts = "Full-screen reminder alerts",
    fullScreenPermissionUnavailableWarning = "Android is blocking full-screen alerts for this app. Reminders will still appear as high-priority notifications.",
    openAndroidSettings = "Open Android settings",
    fullScreenAlertDismiss = "Dismiss",
    fullScreenAlertOpenApp = "Open app",
    notificationError = "Something went wrong. Please try again.",
    notificationDefaultBody = "Keep going!",
    myStreak = "My streak",
    changeStartTime = "Change start time",
    resetToNow = "Reset to now",
    resetCounterTitle = "Reset your streak?",
    resetCounterBody = "Your counter will restart from zero. This cannot be undone.",
    confirmReset = "Reset",
    counterStartedAt = "Started",
    counterAccessibility = { days, hours, minutes, seconds ->
        "Streak: $days days, $hours hours, $minutes minutes, $seconds seconds"
    },
    startTimeFutureError = "Choose a time that is not in the future.",
    datePickerTitle = "Select date",
    datePickerHeadline = { date -> EnglishDatePickerHeadlineFormatter.format(date) },
    counterUnitLabels = EnglishCounterUnitLabels,
    weekdayInitials = listOf("S", "M", "T", "W", "T", "F", "S"),
    weekdayNames = listOf("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday")
)

private val HebrewStrings = AppStrings(
    appName = "SimpleNoFap",
    main = "ראשי",
    notifications = "ניהול התראות",
    settings = "הגדרות",
    counter = "מונה",
    dayStreaks = "רצפי ימים",
    language = "שפה",
    languageEnglish = "אנגלית",
    languageHebrew = "עברית",
    languageSystem = "לפי המערכת",
    theme = "ערכת נושא",
    themeLight = "בהיר",
    themeDark = "כהה",
    themeSystem = "לפי המערכת",
    profile = "פרופיל",
    name = "שם",
    namePlaceholder = "איך לפנות אליך?",
    nameSupportingText = "השם משמש לעידוד אישי יותר.",
    nameRequired = "יש להזין שם.",
    nameSaved = "השם נשמר.",
    save = "שמירה",
    appearance = "מראה",
    appearanceDescription = "בחרו כיצד SimpleNoFap תיראה במכשיר הזה.",
    languageDescription = "בחרו את שפת האפליקציה ואת כיוון הקריאה.",
    about = "אודות",
    version = "גרסה",
    versionUnavailable = "לא זמינה",
    aboutPurpose = "שותף פשוט ופרטי שעוזר לשמור על המיקוד ברצף שלך.",
    unitedStatesFlag = "דגל ארצות הברית",
    israelFlag = "דגל ישראל",
    mainPlaceholder = "מסך ראשי זמני",
    counterPlaceholder = "כאן יופיע מונה הרצף.",
    dayStreaksPlaceholder = "כאן יופיעו תגי רצפי הימים האחרונים והזמינים.",
    dayStreakThreeDaysName = "\u05e9\u05dc\u05d5\u05e9\u05d4 \u05d9\u05de\u05d9\u05dd",
    dayStreakOneWeekName = "\u05e9\u05d1\u05d5\u05e2 \u05d0\u05d7\u05d3",
    dayStreakThreeWeeksName = "\u05e9\u05dc\u05d5\u05e9\u05d4 \u05e9\u05d1\u05d5\u05e2\u05d5\u05ea",
    dayStreakOneMonthName = "\u05d7\u05d5\u05d3\u05e9 \u05d0\u05d7\u05d3",
    dayStreakTwoMonthsName = "\u05d7\u05d5\u05d3\u05e9\u05d9\u05d9\u05dd",
    dayStreakThresholdDays = { days -> "$days \u05d9\u05de\u05d9\u05dd" },
    dayStreakOverview = "\u05d4\u05d9\u05e9\u05d2\u05d9\u05dd",
    dayStreakNextAchievement = "\u05d4\u05d4\u05d9\u05e9\u05d2 \u05d4\u05d1\u05d0",
    dayStreakAllAchievementsEarned = "\u05db\u05dc \u05d4\u05d4\u05d9\u05e9\u05d2\u05d9\u05dd \u05dc\u05e0\u05d9\u05e1\u05d9\u05d5\u05df \u05d4\u05d6\u05d4 \u05d4\u05d5\u05e9\u05d2\u05d5",
    dayStreakRemainingTime = { days, hours, minutes -> "\u05e0\u05d5\u05ea\u05e8\u05d5 ${days}\u05d9 ${hours}\u05e9 ${minutes}\u05d3" },
    dayStreakAvailableRewards = "\u05e4\u05e8\u05e1\u05d9\u05dd \u05d6\u05de\u05d9\u05e0\u05d9\u05dd",
    dayStreakCurrentAttempt = "\u05d4\u05e0\u05d9\u05e1\u05d9\u05d5\u05df \u05d4\u05e0\u05d5\u05db\u05d7\u05d9",
    dayStreakEarned = "\u05d4\u05d5\u05e9\u05d2",
    dayStreakLocked = "\u05e0\u05e2\u05d5\u05dc",
    dayStreakAvailableCount = { count -> "$count \u05d6\u05de\u05d9\u05df" },
    dayStreakHistory = "\u05d4\u05d9\u05e1\u05d8\u05d5\u05e8\u05d9\u05d4 \u05d0\u05d7\u05e8\u05d5\u05e0\u05d4",
    dayStreakNoHistory = "\u05e2\u05d3\u05d9\u05d9\u05df \u05d0\u05d9\u05df \u05e4\u05e8\u05e1\u05d9 Day-Streak.",
    dayStreakEarnedAt = { value -> "\u05d4\u05d5\u05e9\u05d2 $value" },
    dayStreakUsedAt = { value -> "\u05e9\u05d5\u05de\u05e9 $value" },
    dayStreakCooldownReady = "\u05e9\u05de\u05d9\u05e8\u05ea \u05e4\u05e8\u05e1 \u05d6\u05de\u05d9\u05e0\u05d4.",
    dayStreakCooldownWaiting = { value -> "\u05d4\u05de\u05ea\u05e0\u05d4 \u05dc\u05e4\u05e8\u05e1: \u05e0\u05d5\u05ea\u05e8 $value" },
    dayStreakCelebrationTitle = "\u05d4\u05d9\u05e9\u05d2 Day-Streak \u05e0\u05e4\u05ea\u05d7",
    dayStreakCelebrationBody = { name -> "\u05e4\u05e8\u05e1 $name \u05e0\u05d5\u05e1\u05e3 \u05dc\u05e9\u05de\u05d9\u05e8\u05d5\u05ea \u05e9\u05dc\u05da." },
    dismiss = "\u05e1\u05d2\u05d9\u05e8\u05d4",
    relapseTitle = "\u05ea\u05de\u05d9\u05db\u05d4 \u05d1\u05de\u05e2\u05d9\u05d3\u05d4",
    relapseUseRewardBody = "\u05d0\u05e4\u05e9\u05e8 \u05dc\u05d4\u05e9\u05ea\u05de\u05e9 \u05d1\u05e4\u05e8\u05e1 Day-Streak \u05d6\u05de\u05d9\u05df \u05db\u05d3\u05d9 \u05dc\u05e9\u05de\u05d5\u05e8 \u05d0\u05ea \u05d4\u05de\u05d5\u05e0\u05d4.",
    relapseNoRewardBody = "\u05e2\u05d3\u05d9\u05d9\u05df \u05d0\u05d9\u05df \u05e4\u05e8\u05e1 Day-Streak \u05d6\u05de\u05d9\u05df. \u05d0\u05e4\u05e9\u05e8 \u05dc\u05d0\u05e4\u05e1 \u05d5\u05dc\u05d4\u05ea\u05d7\u05d9\u05dc \u05e0\u05d9\u05e1\u05d9\u05d5\u05df \u05d7\u05d3\u05e9.",
    relapseCooldownBody = { value -> "\u05e4\u05e8\u05e1 \u05e9\u05d5\u05de\u05e9 \u05dc\u05d0\u05d7\u05e8\u05d5\u05e0\u05d4. \u05d0\u05e4\u05e9\u05e8 \u05dc\u05e9\u05de\u05d5\u05e8 \u05e9\u05d5\u05d1 \u05d1\u05e2\u05d5\u05d3 $value, \u05d0\u05d5 \u05dc\u05d0\u05e4\u05e1 \u05e2\u05db\u05e9\u05d9\u05d5." },
    resetAnyway = "\u05dc\u05d0\u05e4\u05e1 \u05d1\u05db\u05dc \u05d6\u05d0\u05ea",
    useReward = "\u05d4\u05e9\u05ea\u05de\u05e9 \u05d1\u05e4\u05e8\u05e1",
    rewardUseFailed = "\u05dc\u05d0 \u05e0\u05d9\u05ea\u05df \u05dc\u05d4\u05e9\u05ea\u05de\u05e9 \u05d1\u05e4\u05e8\u05e1. \u05e0\u05e1\u05d5 \u05e9\u05d5\u05d1.",
    dayStreakThreeDaysNotificationTitle = "\u05e9\u05dc\u05d5\u05e9\u05d4 \u05d9\u05de\u05d9\u05dd \u05e9\u05dc \u05db\u05d5\u05d7!",
    dayStreakThreeDaysNotificationBody = "\u05e2\u05d1\u05e8\u05ea \u05d0\u05ea \u05e9\u05dc\u05d5\u05e9\u05ea \u05d4\u05d9\u05de\u05d9\u05dd \u05d4\u05e8\u05d0\u05e9\u05d5\u05e0\u05d9\u05dd. \u05de\u05de\u05e9\u05d9\u05db\u05d9\u05dd \u05dc\u05d1\u05e0\u05d5\u05ea \u05d0\u05ea \u05d4\u05e8\u05e6\u05e3 - \u05d4\u05de\u05d5\u05de\u05e0\u05d8\u05d5\u05dd \u05e9\u05dc\u05da \u05d0\u05de\u05d9\u05ea\u05d9.",
    dayStreakOneWeekNotificationTitle = "\u05e9\u05d1\u05d5\u05e2 \u05e9\u05dc\u05dd!",
    dayStreakOneWeekNotificationBody = "\u05e9\u05d1\u05e2\u05d4 \u05d9\u05de\u05d9\u05dd \u05e9\u05dc \u05d4\u05ea\u05de\u05d3\u05d4. \u05d4\u05d5\u05db\u05d7\u05ea \u05dc\u05e2\u05e6\u05de\u05da \u05e9\u05d9\u05e9 \u05dc\u05da \u05d0\u05ea \u05d4\u05db\u05d5\u05d7 \u05dc\u05d4\u05de\u05e9\u05d9\u05da.",
    dayStreakThreeWeeksNotificationTitle = "\u05e9\u05dc\u05d5\u05e9\u05d4 \u05e9\u05d1\u05d5\u05e2\u05d5\u05ea \u05d7\u05d6\u05e7\u05d9\u05dd!",
    dayStreakThreeWeeksNotificationBody = "21 \u05d9\u05de\u05d9\u05dd \u05e9\u05dc \u05d1\u05d7\u05d9\u05e8\u05d4 \u05d1\u05e2\u05e6\u05de\u05da. \u05d4\u05de\u05d7\u05d5\u05d9\u05d1\u05d5\u05ea \u05e9\u05dc\u05da \u05db\u05d1\u05e8 \u05d4\u05d5\u05e4\u05db\u05ea \u05dc\u05d4\u05e8\u05d2\u05dc.",
    dayStreakOneMonthNotificationTitle = "\u05d7\u05d5\u05d3\u05e9 \u05e9\u05dc\u05dd!",
    dayStreakOneMonthNotificationBody = "30 \u05d9\u05de\u05d9\u05dd \u05e9\u05dc \u05de\u05d7\u05d5\u05d9\u05d1\u05d5\u05ea. \u05d6\u05d4 \u05d4\u05d9\u05e9\u05d2 \u05d2\u05d3\u05d5\u05dc - \u05de\u05de\u05e9\u05d9\u05db\u05d9\u05dd \u05dc\u05e9\u05de\u05d5\u05e8 \u05e2\u05dc \u05de\u05d4 \u05e9\u05d1\u05e0\u05d9\u05ea.",
    dayStreakTwoMonthsNotificationTitle = "\u05d7\u05d5\u05d3\u05e9\u05d9\u05d9\u05dd \u05e9\u05dc \u05e2\u05d5\u05e6\u05de\u05d4!",
    dayStreakTwoMonthsNotificationBody = "60 \u05d9\u05de\u05d9\u05dd \u05e9\u05dc \u05d4\u05ea\u05de\u05d3\u05d4. \u05d4\u05d2\u05e2\u05ea \u05e8\u05d7\u05d5\u05e7, \u05d5\u05d4\u05db\u05d5\u05d7 \u05dc\u05d4\u05de\u05e9\u05d9\u05da \u05e0\u05de\u05e6\u05d0 \u05d0\u05e6\u05dc\u05da.",
    notificationsPlaceholder = "כאן יופיע ניהול ההתראות המתוזמנות.",
    settingsPlaceholder = "העדפות האפליקציה עבור שלד הממשק.",
    openMenu = "פתח תפריט",
    addNotification = "הוספת התראה",
    noNotifications = "עדיין אין תזכורות",
    noNotificationsBody = "הוסיפו תזכורת שבועית כדי לשמור על המיקוד ברצף.",
    editNotification = "עריכת תזכורת",
    newNotification = "תזכורת חדשה",
    cancel = "ביטול",
    delete = "מחיקה",
    deleteNotificationTitle = "למחוק את התזכורת?",
    deleteNotificationBody = "התזכורת והשעון המתוזמן שלה יימחקו.",
    discardChangesTitle = "לבטל את השינויים?",
    discardChangesBody = "השינויים שלא נשמרו יאבדו.",
    discard = "ביטול שינויים",
    keepEditing = "המשך עריכה",
    message = "הודעה",
    messageOptional = "עידוד אופציונלי",
    sound = "צליל",
    defaultSound = "ברירת המחדל של המערכת",
    silent = "שקט",
    chooseSound = "בחירת צליל",
    weekdaysRequired = "יש לבחור לפחות יום אחד.",
    notificationPermissionWarning = "ההתראות חסומות. תזכורות פעילות נשמרות אך לא ניתן להציג אותן.",
    grantPermission = "אישור התראות",
    exactAlarmWarning = "הגישה להתראות מדויקות כבויה. ייתכן עיכוב קל בתזכורות.",
    allowExactAlarms = "התראות ותזכורות",
    notificationBehavior = "\u05d0\u05d5\u05e4\u05df \u05d4\u05ea\u05e8\u05d0\u05d5\u05ea",
    notificationBehaviorDescription = "\u05d1\u05d7\u05e8\u05d5 \u05db\u05d9\u05e6\u05d3 \u05ea\u05d6\u05db\u05d5\u05e8\u05d5\u05ea \u05de\u05ea\u05d5\u05d6\u05de\u05e0\u05d5\u05ea \u05d9\u05d5\u05e4\u05d9\u05e2\u05d5.",
    normalReminderNotifications = "\u05d4\u05ea\u05e8\u05d0\u05d5\u05ea \u05e8\u05d2\u05d9\u05dc\u05d5\u05ea",
    fullScreenReminderAlerts = "\u05d4\u05ea\u05e8\u05d0\u05d5\u05ea \u05ea\u05d6\u05db\u05d5\u05e8\u05ea \u05d1\u05de\u05e1\u05da \u05de\u05dc\u05d0",
    fullScreenPermissionUnavailableWarning = "\u05d0\u05e0\u05d3\u05e8\u05d5\u05d0\u05d9\u05d3 \u05d7\u05d5\u05e1\u05dd \u05d4\u05ea\u05e8\u05d0\u05d5\u05ea \u05de\u05e1\u05da \u05de\u05dc\u05d0 \u05dc\u05d0\u05e4\u05dc\u05d9\u05e7\u05e6\u05d9\u05d4 \u05d6\u05d5. \u05d4\u05ea\u05d6\u05db\u05d5\u05e8\u05d5\u05ea \u05e2\u05d3\u05d9\u05d9\u05df \u05d9\u05d5\u05e4\u05d9\u05e2\u05d5 \u05db\u05d4\u05ea\u05e8\u05d0\u05d5\u05ea \u05d1\u05e2\u05d3\u05d9\u05e4\u05d5\u05ea \u05d2\u05d1\u05d5\u05d4\u05d4.",
    openAndroidSettings = "\u05e4\u05ea\u05d9\u05d7\u05ea \u05d4\u05d2\u05d3\u05e8\u05d5\u05ea \u05d0\u05e0\u05d3\u05e8\u05d5\u05d0\u05d9\u05d3",
    fullScreenAlertDismiss = "\u05e1\u05d2\u05d9\u05e8\u05d4",
    fullScreenAlertOpenApp = "\u05e4\u05ea\u05d9\u05d7\u05ea \u05d4\u05d0\u05e4\u05dc\u05d9\u05e7\u05e6\u05d9\u05d4",
    notificationError = "משהו השתבש. נסו שוב.",
    notificationDefaultBody = "ממשיכים קדימה!",
    myStreak = "הרצף שלי",
    changeStartTime = "שינוי זמן ההתחלה",
    resetToNow = "איפוס לעכשיו",
    resetCounterTitle = "לאפס את הרצף?",
    resetCounterBody = "המונה יתחיל מחדש מאפס. לא ניתן לבטל פעולה זו.",
    confirmReset = "איפוס",
    counterStartedAt = "התחלה",
    counterAccessibility = { days, hours, minutes, seconds ->
        "רצף: $days ימים, $hours שעות, $minutes דקות, $seconds שניות"
    },
    startTimeFutureError = "יש לבחור זמן שאינו בעתיד.",
    datePickerTitle = "\u05d1\u05d7\u05d9\u05e8\u05ea \u05ea\u05d0\u05e8\u05d9\u05da",
    datePickerHeadline = { date -> HebrewDatePickerHeadlineFormatter.format(date) },
    counterUnitLabels = CounterUnitLabels(
        year = "שנה",
        years = "שנים",
        month = "חודש",
        months = "חודשים",
        week = "שבוע",
        weeks = "שבועות",
        day = "יום",
        days = "ימים"
    ),
    weekdayInitials = listOf("א", "ב", "ג", "ד", "ה", "ו", "ש"),
    weekdayNames = listOf("יום ראשון", "יום שני", "יום שלישי", "יום רביעי", "יום חמישי", "יום שישי", "שבת")
)
